"""add timestamps to todos

Revision ID: 6f2e2a367119
Revises: 410d3354833c
Create Date: 2026-09-23 22:01:44.824069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2e2a367119'
down_revision: Union[str, Sequence[str], None] = '410d3354833c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), nullable=True))
   


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
